version: '3.9'
services:
  webserver:
    container_name: ems_stage_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "8004:80"             # Staging web interface (Host port 8004 -> Container port 80)
    depends_on:
      - mysql-db
    networks:
      - ems_stage_network

  mysql-db:
    container_name: ems_stage_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ems_stage_db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "StageRootPass###123"
      MYSQL_DATABASE: ems_stage_db
      MYSQL_USER: ems_stage_user
      MYSQL_PASSWORD: "StagePass###123"
    ports:
      - "3309:3306"           # Staging database (Host port 3309 -> Container port 3306)
    networks:
      - ems_stage_network

  cronjob:
    container_name: ems_stage_cron
    build:
      context: .
      dockerfile: cron/Dockerfile
    depends_on:
      - webserver
    networks:
      - ems_stage_network

  ems_qr_service:
    container_name: ems_stage_qr
    build:
      context: .
      dockerfile: qr_service/Dockerfile
    ports:
      - "8005:8000"           # Staging QR service (Host port 8005 -> Container port 8000)
    depends_on:
      - webserver
    networks:
      - ems_stage_network

networks:
  ems_stage_network:
    driver: bridge

volumes:
  ems_stage_db:
